// GENERATED FILE — DO NOT EDIT.
// Regenerate with: dart run ffigen --config ffigen.yaml
//
// ignore_for_file: type=lint, unused_field, unused_element, camel_case_types

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// Dart FFI bindings for the C-ABI wrapper around whisper.cpp.
/// Generated from ios/whisper/wrapper.h. Do not hand-edit.
///
class WhisperBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  WhisperBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  WhisperBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  int spike_transcribe_wav(
    ffi.Pointer<ffi.Char> model_path,
    ffi.Pointer<ffi.Char> wav_path,
    ffi.Pointer<ffi.Char> out_buf,
    int buf_size,
  ) {
    return _spike_transcribe_wav(model_path, wav_path, out_buf, buf_size);
  }

  late final _spike_transcribe_wavPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Int,
          )
        >
      >('spike_transcribe_wav');
  late final _spike_transcribe_wav = _spike_transcribe_wavPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          int,
        )
      >();
}
